services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emtlab
      POSTGRES_PASSWORD: emtlab
      POSTGRES_DB: emt_shoplab
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - 2345:5432
volumes:
  pgdata:
